### ISSUE TITLE
Port `EnumMacros#materializeEnumImpl `

### ISSUE THREAD

**Issue by lloydmeta** [lloydmeta/mune#2]
https://github.com/lloydmeta/enumeratum/blob/d91d191cd11a630cc4d1b7cc6c82decdf436ac1b/macros/src/main/scala/enumeratum/EnumMacros.scala#L23-L62

**Comment by lloydmeta** [comment]
Current implementation

https://github.com/lloydmeta/mune/blob/dfa76016600c26fe3e71cd3894d7a10615218db6/src/main/scala/EnumMacros.scala#L52-L106

 is running into 

```
[error] -- Error: /Users/lloyd/Documents/skala/mune/src/test/scala/Test1.scala:13:49 ---
[error] 13 |    assertEquals(SomeEnum, getEnumForEntry(entry))
[error]    |                                                 ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.Exception: Expr cast exception: SomeEnum
[error]    |of type: SomeEnum
[error]    |did not conform to type: TestEnumEntry & TestEnum[SomeEnum]
[error]    |
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:71)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:113)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TreeMethods$.asExprOf(QuotesImpl.scala:112)
[error]    |	at EnumMacros$._materializeEnumImpl(EnumMacros.scala:96)
[error]    |	at EnumMacros$.inline$_materializeEnumImpl(EnumMacros.scala:52)
[error]    |
[error]    | This location contains code that was inlined from Test1.scala:13
[error]    | This location contains code that was inlined from Test1.scala:28
[error] one error found
```

**Comment by tpunder** [comment]
Does https://github.com/lloydmeta/mune/pull/4 help?

**Comment by lloydmeta** [comment]
Done, thanks @tpunder !
